// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MyToDoList.DbContexts;
using MyToDoList.Enums;
using System;

namespace MyToDoList.Migrations
{
    [DbContext(typeof(MyToDoListDbContext))]
    [Migration("20171107222712_07.11.2017")]
    partial class _07112017
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyToDoList.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MyToDoList.Entities.CurrentWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("MondayDate");

                    b.HasKey("Id");

                    b.ToTable("CurrentWeeks");
                });

            modelBuilder.Entity("MyToDoList.Entities.Duty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryId");

                    b.Property<string>("Content");

                    b.Property<int>("CurrentWeekId");

                    b.Property<int>("Day");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CurrentWeekId");

                    b.ToTable("Duties");
                });

            modelBuilder.Entity("MyToDoList.Entities.Duty", b =>
                {
                    b.HasOne("MyToDoList.Entities.Category", "Category")
                        .WithMany("Duties")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyToDoList.Entities.CurrentWeek", "CurrentWeek")
                        .WithMany("DoneDuties")
                        .HasForeignKey("CurrentWeekId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
